on:
  workflow_dispatch:
  schedule:
    - cron: "01 23 1-5 * *"
name: Run Short Tracker
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: python3 -m pip install .
      - name: Collect Data
        run: python3 src/short_tracker/data_main.py
      - name: Calculate and Format Results
        run: python3 src/short_tracker/metrics.py
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
