on:
  workflow_dispatch:
  schedule:
    - cron: "01 23 1-5 * *"
name: Run Short Tracker
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build
        run: python3 -m pip install --user -e .
      - name: Collect Data
        run: |
          sudo chmod ugo+rwx data/data.sqlite
          ls -la data/
          python3 src/short_tracker/data_main.py
      - name: Calculate and Format Results
        run: python3 src/short_tracker/metrics.py
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
